---
- name: 复制管理主机公钥到托管节点
  authorized_key:
    user: deploy
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  tags: copy
- name: 移除托管节点上管理主机公钥
  authorized_key:
    user: deploy
    state: absent
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  tags: remove